Data Cleaning and Exploration
Indicated damage is the class label we want to predict

In [126]:
import pandas as pd

In [127]:
missing_values = ["UNKNOWN", "Unknown"]
train_data = pd.read_csv('train.csv', na_values=missing_values, header='infer')
print("Number of rows and columns in training data: ", train_data.shape)
train_data.head()
train_data.info()

# test_data = pd.read_csv('test.csv', header='infer')
# test_data.head()

/var/folders/j1/9v5pdr3x0yq9w6b8wmphvp2c0000gn/T/ipykernel_53641/1644209056.py:2: DtypeWarning: Columns (8,9,20) have mixed types. Specify dtype option on import or set low_memory=False.
  train_data = pd.read_csv('train.csv', na_values=missing_values, header='infer')

Number of rows and columns in training data:  (307178, 55)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 307178 entries, 0 to 307177
Data columns (total 55 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   INDEX_NR              307178 non-null  int64
 1   INCIDENT_DATE         307178 non-null  object
 2   INCIDENT_MONTH        307178 non-null  int64
 3   INCIDENT_YEAR         307178 non-null  int64
 4   TIME                  197926 non-null  object
 5   TIME_OF_DAY           173207 non-null  object
 6   AIRPORT_ID            307178 non-null  object
 7   AIRPORT               266494 non-null  object
 8   LATITUDE              266434 non-null  object
 9   LONGITUDE             266431 non-null  object
 10  RUNWAY                231592 non-null  object
 11  STATE                 266434 non-null  object
 12  FAAREGION             266434 non-null  object
 13  LOCATION              39217 non-null   object
 14  OPID                  307178 non-null  object
 15  OPERATOR              220486 non-null  object
 16  REG                   188187 non-null  object
 17  FLT                   145740 non-null  object
 18  AIRCRAFT              220236 non-null  object
 19  AMA                   218282 non-null  object
 20  AMO                   190365 non-null  object
 21  EMA                   204757 non-null  float64
 22  EMO                   194002 non-null  float64
 23  AC_CLASS              219863 non-null  object
 24  AC_MASS               219732 non-null  float64
 25  TYPE_ENG              219392 non-null  object
 26  NUM_ENGS              219481 non-null  float64
 27  ENG_1_POS             219461 non-null  float64
 28  ENG_2_POS             204669 non-null  float64
 29  ENG_3_POS             12356 non-null   float64
 30  ENG_4_POS             3269 non-null    float64
 31  PHASE_OF_FLIGHT       186208 non-null  object
 32  HEIGHT                152981 non-null  float64
 33  SPEED                 95102 non-null   float64
 34  DISTANCE              203875 non-null  float64
 35  SKY                   144353 non-null  object
 36  PRECIPITATION         11212 non-null   object
 37  BIRD_BAND_NUMBER      713 non-null     object
 38  SPECIES_ID            307178 non-null  object
 39  SPECIES               307178 non-null  object
 40  OUT_OF_RANGE_SPECIES  307178 non-null  int64
 41  REMARKS               271873 non-null  object
 42  REMAINS_COLLECTED     307178 non-null  int64
 43  REMAINS_SENT          307178 non-null  int64
 44  WARNED                116043 non-null  object
 45  NUM_SEEN              98632 non-null   object
 46  NUM_STRUCK            306531 non-null  object
 47  SIZE                  273671 non-null  object
 48  ENROUTE_STATE         5346 non-null    object
 49  COMMENTS              204095 non-null  object
 50  SOURCE                307178 non-null  object
 51  PERSON                288210 non-null  object
 52  LUPDATE               307178 non-null  object
 53  TRANSFER              307178 non-null  int64
 54  INDICATED_DAMAGE      307178 non-null  int64
dtypes: float64(11), int64(8), object(36)
memory usage: 128.9+ MB

In [128]:
train_data.describe()

,INDEX_NR,INCIDENT_MONTH,INCIDENT_YEAR,EMA,EMO,AC_MASS,NUM_ENGS,ENG_1_POS,ENG_2_POS,ENG_3_POS,ENG_4_POS,HEIGHT,SPEED,DISTANCE,OUT_OF_RANGE_SPECIES,REMAINS_COLLECTED,REMAINS_SENT,TRANSFER,INDICATED_DAMAGE
count,3.071780e+05,307178.000000,307178.000000,204757.000000,194002.00000,219732.000000,219481.000000,219461.000000,204669.000000,12356.000000,3269.000000,152981.000000,95102.000000,203875.000000,307178.000000,307178.000000,307178.000000,307178.0,307178.000000
mean,1.030746e+06,7.221136,2013.629697,19.308815,8.15889,3.557770,2.004328,2.722128,2.546287,2.909922,2.162435,882.259627,142.973061,0.878159,0.000856,0.538925,0.179821,0.0,0.063569
std,3.851711e+05,2.750603,8.991125,10.573812,11.50024,0.865756,0.409663,2.117692,1.958387,1.938278,1.466136,1858.178379,46.550616,3.687059,0.029248,0.498483,0.384039,0.0,0.243984
min,6.082420e+05,1.000000,1990.000000,1.000000,0.00000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000
25%,7.054882e+05,5.000000,2008.000000,10.000000,1.00000,3.000000,2.000000,1.000000,1.000000,1.000000,1.000000,0.000000,120.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000
50%,8.052665e+05,8.000000,2015.000000,22.000000,4.00000,4.000000,2.000000,1.000000,1.000000,1.000000,1.000000,50.000000,140.000000,0.000000,0.000000,1.000000,0.000000,0.0,0.000000
75%,1.437907e+06,9.000000,2021.000000,31.000000,10.00000,4.000000,2.000000,5.000000,5.000000,5.000000,4.000000,1000.000000,160.000000,0.000000,0.000000,1.000000,0.000000,0.0,0.000000
max,1.825451e+06,12.000000,2026.000000,47.000000,97.00000,5.000000,4.000000,7.000000,7.000000,6.000000,5.000000,32000.000000,541.000000,99.000000,1.000000,1.000000,1.000000,0.0,1.000000

In [129]:
# Handling missing values
null_column_totals = train_data.isnull().sum().sort_values(ascending=False)
print("Number missing values for each column\n", null_column_totals)

Number missing values for each column
 BIRD_BAND_NUMBER        306465
ENG_4_POS               303909
ENROUTE_STATE           301832
PRECIPITATION           295966
ENG_3_POS               294822
LOCATION                267961
SPEED                   212076
NUM_SEEN                208546
WARNED                  191135
SKY                     162825
FLT                     161438
HEIGHT                  154197
TIME_OF_DAY             133971
PHASE_OF_FLIGHT         120970
REG                     118991
AMO                     116813
EMO                     113176
TIME                    109252
DISTANCE                103303
COMMENTS                103083
ENG_2_POS               102509
EMA                     102421
AMA                      88896
TYPE_ENG                 87786
ENG_1_POS                87717
NUM_ENGS                 87697
AC_MASS                  87446
AC_CLASS                 87315
AIRCRAFT                 86942
OPERATOR                 86692
RUNWAY                   75586
LONGITUDE                40747
STATE                    40744
FAAREGION                40744
LATITUDE                 40744
AIRPORT                  40684
REMARKS                  35305
SIZE                     33507
PERSON                   18968
NUM_STRUCK                 647
SOURCE                       0
LUPDATE                      0
TRANSFER                     0
INDEX_NR                     0
REMAINS_SENT                 0
REMAINS_COLLECTED            0
OUT_OF_RANGE_SPECIES         0
SPECIES                      0
SPECIES_ID                   0
INCIDENT_DATE                0
OPID                         0
AIRPORT_ID                   0
INCIDENT_YEAR                0
INCIDENT_MONTH               0
INDICATED_DAMAGE             0
dtype: int64

In [130]:
# remove any duplicates
print("Number of duplicate rows", train_data.duplicated().sum())
train_data.drop_duplicates()
# Shape of dataset remained the same, no duplicates found in training dataset

Number of duplicate rows 0

,INDEX_NR,INCIDENT_DATE,INCIDENT_MONTH,INCIDENT_YEAR,TIME,TIME_OF_DAY,AIRPORT_ID,AIRPORT,LATITUDE,LONGITUDE,...,NUM_SEEN,NUM_STRUCK,SIZE,ENROUTE_STATE,COMMENTS,SOURCE,PERSON,LUPDATE,TRANSFER,INDICATED_DAMAGE
0,1410120,12/13/93,12,1993,NaN,Day,TJSJ,LUIS MUNOZ MARIN INTL,18.43942,-66.00183,...,10-Feb,10-Feb,Small,NaN,NaN,FAA Form 5200-7,Pilot,4/3/23,0,0
1,709688,2/1/10,2,2010,5:00,Night,WMKK,KUALA LUMPUR INTL,2.745578,101.709917,...,NaN,1,Medium,NaN,2010-5-18-53374 /Legacy Record 300758/,FAA Form 5200-7-E,Air Transport Operations,6/9/10,0,0
2,730841,5/9/12,5,2012,2:00,Night,KSDF,MUHAMMAD ALI INTERNATIONAL,38.17439,-85.736,...,NaN,1,Large,NaN,UPS EVENT REPT 36216 (4/22/13 UPDATED COST) /L...,Air Transport Report,Air Transport Operations,4/22/13,0,1
3,654676,10/8/02,10,2002,NaN,NaN,KLAX,LOS ANGELES INTL,33.94254,-118.40807,...,NaN,10-Feb,Medium,NaN,2002-10-8-111929 /Legacy Record 216397/,FAA Form 5200-7-E,Carcass Found,1/9/03,0,0
4,629708,2/3/97,2,1997,NaN,Dawn,PHLI,LIHUE ARPT,21.97598,-159.33896,...,1,1,Medium,NaN,SOURCE 5200-7 & PACIR /Legacy Record 121531/,Multiple,NaN,3/1/07,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
307173,1786439,10/31/25,10,2025,,NaN,KVNC,VENICE MUNICIPAL AIRPORT,27.07161,-82.44033,...,NaN,1,Medium,NaN,NaN,FAA Form 5200-7-E,Carcass Found,1/2/26,0,0
307174,676049,8/20/06,8,2006,NaN,NaN,KORD,CHICAGO O'HARE INTL ARPT,41.9796,-87.90446,...,NaN,1,Small,NaN,2006-9-5-121657 /Legacy Record 237856/,FAA Form 5200-7-E,Carcass Found,11/16/06,0,0
307175,991735,5/31/19,5,2019,11:59,NaN,KTOA,ZAMPERINI FIELD ARPT,33.80338,-118.3396,...,NaN,1,Small,NaN,NaN,MOR,Tower,6/17/20,0,0
307176,1525457,6/22/20,6,2020,8:42,NaN,KDAL,DALLAS LOVE FIELD ARPT,32.84711,-96.85177,...,NaN,1,Small,NaN,NaN,FAA Form 5200-7-E,Carcass Found,5/20/24,0,0
307177,760473,9/5/14,9,2014,NaN,NaN,KCID,THE EASTERN IOWA ARPT,41.88459,-91.71087,...,NaN,10-Feb,Small,NaN,2014-9-5-085953 /Legacy Record 352712/,FAA Form 5200-7-E,Carcass Found,2/13/15,0,0

In [131]:
# Drop columns that do not relate to prediction: remarks and comments
# Drop columns with less than 70% of row values filled
# BIRD_BAND_NUMBER        306465
# ENG_4_POS               303909
# ENROUTE_STATE           301832
# PRECIPITATION           295966
# ENG_3_POS               294822
# LOCATION                267961
# SPEED                   212076
# NUM_SEEN                208546
# WARNED                  191135
# SKY                     162825
# FLT                     161438
# HEIGHT                  154197
# TIME_OF_DAY             133971
# PHASE_OF_FLIGHT         120970
# REG                     118991
# AMO                     116813
# EMO                     113176
# TIME                    109252
# DISTANCE                103303
# COMMENTS                103083
# ENG_2_POS               102509
# EMA                     102421
print(train_data.shape)
train_data = train_data.drop(columns=["REMARKS", "COMMENTS", "BIRD_BAND_NUMBER", "ENG_4_POS", "ENROUTE_STATE", "PRECIPITATION"])
print(train_data.shape)

# Drop Airports and keep airport id
# Drop location or standardize: many null values, inconsistent data format: FOUND AT KATL; DRO-DEN; Found KMEM; Waldorf, MD, 15 MILES KADW
# Drop OPERATOR since we have OPID
# Drop PRECIPITATION: MANYYY Empty values
# Drop BIRD_BAND_ID: Barely any data
# Drop SPECIES: We have species id so no need for species
# ENROUTE_STATE: Pretty empty
# COMMENTS just notes
# Drop Source: may not be needed to predict indicated damage
# Drop Person: dont need for prediction

# NUM_SEEN Needs to be standardized

(307178, 55)
(307178, 53)

In [132]:
print(train_data.columns)
missing = [col for col in categorical_columns if col not in train_data.columns]
print("Missing columns:", missing)

Index(['INDEX_NR', 'INCIDENT_DATE', 'INCIDENT_MONTH', 'INCIDENT_YEAR', 'TIME',
       'TIME_OF_DAY', 'AIRPORT_ID', 'AIRPORT', 'LATITUDE', 'LONGITUDE',
       'RUNWAY', 'STATE', 'FAAREGION', 'LOCATION', 'OPID', 'OPERATOR', 'REG',
       'FLT', 'AIRCRAFT', 'AMA', 'AMO', 'EMA', 'EMO', 'AC_CLASS', 'AC_MASS',
       'TYPE_ENG', 'NUM_ENGS', 'ENG_1_POS', 'ENG_2_POS', 'ENG_3_POS',
       'ENG_4_POS', 'PHASE_OF_FLIGHT', 'HEIGHT', 'SPEED', 'DISTANCE', 'SKY',
       'PRECIPITATION', 'BIRD_BAND_NUMBER', 'SPECIES_ID', 'SPECIES',
       'OUT_OF_RANGE_SPECIES', 'REMAINS_COLLECTED', 'REMAINS_SENT', 'WARNED',
       'NUM_SEEN', 'NUM_STRUCK', 'SIZE', 'ENROUTE_STATE', 'SOURCE', 'PERSON',
       'LUPDATE', 'TRANSFER', 'INDICATED_DAMAGE'],
      dtype='object')
Missing columns: []

In [133]:
# need to one hot encode categorical variables
categorical_columns =['TIME_OF_DAY', 'AIRPORT_ID', 'RUNWAY', 'STATE', 'FAAREGION', 'LOCATION', 'OPID', 'AIRCRAFT', 'AC_CLASS', 'TYPE_ENG', 'PHASE_OF_FLIGHT', 'SKY', 'SPECIES_ID', 'WARNED', 'SIZE', 'ENROUTE_STATE', 'SOURCE', 'PERSON']
train_data = pd.get_dummies(train_data, columns = categorical_columns, drop_first=True)


# WHAT TO ONE HOT ENCODE
# TIME_OF_DAY, AIRPORT_ID, RUNWAY, STATE, FAAREGION, LOCATION, OPID, AIRCRAFT, AC_CLASS, TYPE_ENG, PHASE_OF_FLIGHT, SKY, SPECIES_ID, 
# WARNED, SIZE, ENROUTE_STATE, SOURCE, PERSON

In [134]:
train_data.head()

,INDEX_NR,INCIDENT_DATE,INCIDENT_MONTH,INCIDENT_YEAR,TIME,AIRPORT,LATITUDE,LONGITUDE,OPERATOR,REG,...,SOURCE_Multiple,SOURCE_NTSB,SOURCE_Other,SOURCE_PACIR,SOURCE_Transport Canada,PERSON_Airport Operations,PERSON_Carcass Found,PERSON_Other,PERSON_Pilot,PERSON_Tower
0,1410120,12/13/93,12,1993,NaN,LUIS MUNOZ MARIN INTL,18.43942,-66.00183,AMERICAN AIRLINES,N892AA,...,False,False,False,False,False,False,False,False,True,False
1,709688,2/1/10,2,2010,5:00,KUALA LUMPUR INTL,2.745578,101.709917,FEDEX EXPRESS,N608FE,...,False,False,False,False,False,False,False,False,False,False
2,730841,5/9/12,5,2012,2:00,MUHAMMAD ALI INTERNATIONAL,38.17439,-85.736,UPS AIRLINES,N141UP,...,False,False,False,False,False,False,False,False,False,False
3,654676,10/8/02,10,2002,NaN,LOS ANGELES INTL,33.94254,-118.40807,NaN,NaN,...,False,False,False,False,False,False,True,False,False,False
4,629708,2/3/97,2,1997,NaN,LIHUE ARPT,21.97598,-159.33896,ALOHA AIRLINES,NaN,...,True,False,False,False,False,False,False,False,False,False